### PR TITLE
Word lists refactor

### LINKED ISSUE #60: docs.rs fails to build `static-lang-word-lists`
Network access isn't allowed

We should probably stub out the constants or something so it can at least show the main of the docs. This also impacts any crates that depend on `static-lang-word-lists` (e.g. `fontheight`), which is pretty grim

### LINKED ISSUE #62: `static-lang-word-lists`: only decompress words if they're accessed
Currently even reading the metadata of a word list causes it to get decompressed, which seems needless

This would end up being a breaking change, but it would save a lot of computation for crates that filter the lists they want to use at runtime, such as autobase

### PR DESCRIPTION
**Pull request by RickyDaMa**
Moves the lazy-loading nature of the word lists internal to them. This allows us to independently load metadata and the word list itself, which fixes #62. It is a **breaking change**.

The build script now detects when we're building for docs.rs and disables downloading, instead stubbing the word lists, which fixes #60.

### CODE REVIEW

File: static-lang-word-lists/src/word_lists.rs [hunk 1]
```diff
@@ -3,16 +3,24 @@ use std::{
...
 use thiserror::Error;
 
+// TODO: this can be Box<str>
+pub(crate) type Word = String;
+pub(crate) type WordSource = Box<[Word]>;
+
 #[derive(Debug, Serialize, Deserialize)]
 #[serde(deny_unknown_fields)]
 pub(crate) struct WordListMetadata {
+    // TODO: this can be Box<str>
```
Comment (madig) [inline static-lang-word-lists/src/word_lists.rs:19]: What would be the advantage?

**Review by madig — APPROVED** [review]
